name: CustomStats
version: '1.0'
main: org.mamoru.customStats.CustomStats
api-version: '1.16'
commands:
  stats:
    description: Show player statistics
    usage: "/<command> [reload]"
    permission: customstats.use
softdepend:
  - PlaceholderAPI
permissions:
  customstats.use:
    description: Allows using the /stats command
    default: true
  customstats.reload:
    description: Allows reloading the plugin configuration
    default: op
