name: FableStats
version: '1.1'
main: org.mamoru.fableStats.FableStats
api-version: '1.16'
commands:
  stats:
    description: Show player statistics
    usage: "/<command> [reload]"
    permission: fablestats.use
softdepend:
  - PlaceholderAPI
permissions:
  fablestats.use:
    description: Allows using the /stats command
    default: true
  fablestats.reload:
    description: Allows reloading the plugin configuration
    default: op
